sudo: false
language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - pip install pep8 mypy-lang
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip3 install typing; fi

script:
  - make test